version: 2.1
jobs:
  lint:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/node:current
    steps:
      - checkout:
          path: "~/project"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
      - run:
          name: Run linter
          command: npm run lint
  build_and_test:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/node:current
    steps:
      - checkout:
          path: "~/project"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
      - run:
          name: Run tests
          command: npm run test
  deploy:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/node:current
    steps:
      - checkout:
          path: "~/project"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
      - run:
          name: Build
          command: CI= npm run build
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=.next

workflows:
  version: 2
  lint-build-test-and-deploy:
    jobs:
      - lint
      - build_and_test:
          requires:
            - lint
      - deploy:
          requires:
            - build_and_test
