import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl text-blue-400">Hello world</h1>
        <h1 className="text-2xl text-blue-400 animate-pulse">Tailwind is working</h1>

      </main>
    </div>
  )
}

export default Home
